services:
  - type: web
    name: fpl-analyser-backend
    runtime: python
    region: frankfurt
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    plan: free

  - type: web
    name: fpl-analyser-frontend
    runtime: node
    region: frankfurt
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://fpl-analyser-backend.onrender.com
      - key: PORT
        value: 3000
    plan: free

